### ISSUE TITLE
random insertion of julia prompt in output

### ISSUE THREAD

**Issue by ghost** [forio/julia-studio#207] opened 2014-02-23 07:21 UTC
I am beginning with julia. Here is a fibonacci series in julia.

code:
a, b = 1, 1
for i in [1:6]
    println(i, " ", a)  
    n = a + b
    a = b
    b = n
end

output:
sometimes
julia> fibonacci
1 1
2

julia> 
 1
3 2
4 3
5 5
6 8

other times
julia> fibonacci
1 1
2 1

julia> 
3
julia> 
 2
4 3
5 5
6 8

and yet other times
julia> fibonacci
1 1
2 1
3 2
4 3
5 

julia> 
5
6 8

In other words, julia-studio is randomly inserting a julia prompt  in for loop where the  " " space is. This is on Windows 8.1. This happens with julia-studio only. The same code on the same OS run from the julia command line does not produce this problem.
This does not happen on linux mint 16. All software is most recent version.

**Comment by keesvp** [comment] 2014-02-23 14:29
duplicate of #63

**Closed as completed by keesvp** 2014-02-23 14:29 UTC
