### ISSUE TITLE
Crashing on Win 7

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#120] opened 2013-05-10 21:59 UTC
"
This might be a bug I suppose but please comment!

I have successfully installed Julia Studio on two quite separate occasions on Windows 7. ""Successfully""  means running a couple of the tutorials and opening and closing the program several times.

However on both occasions, opening Julia S at a later period failed. 

 Problem Event Name:    APPCRASH
  Application Name: JuliaStudio.exe
  Application Version:  0.0.0.0
  Application Timestamp:    513698ad
  Fault Module Name:    Core.dll
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   513699a2
  Exception Code:   c0000005
  Exception Offset: 00018159
  OS Version:   6.1.7600.2.0.0.256.1
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

I suppose this is a problem with my W7 system but please can you confirm this?
I don't have problems with R for instance or any other major installation.

Thanks very much indeed."

**Comment by WestleyArgentum** [comment] 2013-09-25 21:27
Duplicate of #124 (well, it came in first, but through a separate forum and so the context is lost)

**Closed as completed by WestleyArgentum** 2013-09-25 21:27 UTC
